"""transactions pk to (id, created_at)

Revision ID: 0da3c0e77b31
Revises: 7ec5c01c2ff8
Created: 2026-08-11 03:43:22.589484+00:00

REVIEW CHECKLIST — autogenerate is a draft, not an oracle:

  [ ] Does downgrade() actually reverse upgrade()? Test it.
  [ ] Any new index on a large table -> use postgresql_concurrently=True
      and set this migration non-transactional, or you lock writes.
  [ ] Adding a NOT NULL column to a populated table needs a server_default
      or a three-step deploy.
  [ ] Did autogenerate try to DROP something you meant to keep?
  [ ] Read the generated SQL: `alembic upgrade head --sql`
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0da3c0e77b31"
down_revision: str | None = "7ec5c01c2ff8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
