"""harden model constraints

Revision ID: c0e492405f67
Revises: 0da3c0e77b31
Created: 2026-08-28 03:49:10.138389+00:00

Autogenerate produced the CHECK, the index and the NOT NULL. Three things
were added by hand — see WHAT AUTOGENERATE MISSED below.

REVIEW CHECKLIST — autogenerate is a draft, not an oracle:

  [x] Does downgrade() actually reverse upgrade()? Test it.
      -> Yes; verified with `alembic downgrade -1 && alembic upgrade head`
         and the full `downgrade base` cycle CI runs.
  [x] Any new index on a large table -> use postgresql_concurrently=True
      and set this migration non-transactional, or you lock writes.
      -> Two locking operations here: the audit_events index build and the
         transaction_lines PK swap. Both fine on empty tables; see the
         PRODUCTION NOTE in upgrade() for what changes when they aren't.
  [x] Adding a NOT NULL column to a populated table needs a server_default
      or a three-step deploy.
      -> Autogenerate emitted the ALTER with no backfill, which would fail
         on any row with a NULL memo. Backfill added.
  [x] Did autogenerate try to DROP something you meant to keep?
      -> No.
  [x] Read the generated SQL: `alembic upgrade head --sql`

--------------------------------------------------------------------------
WHAT AUTOGENERATE MISSED
--------------------------------------------------------------------------
1. The transaction_lines primary key swap. Alembic does not detect primary
   key changes at all — the same blind spot that left migration
   0da3c0e77b31 empty. The table still had PRIMARY KEY (created_at, id)
   from declaration order; the model says (id, created_at).

2. The memo backfill. It emitted `ALTER COLUMN memo SET NOT NULL` with no
   UPDATE in front of it. On an empty table that passes and looks correct,
   which is exactly how this class of bug reaches production.

3. The memo length change. The model went from String to String(255), but
   autogenerate emitted `existing_type=sa.VARCHAR()` and altered only
   nullability, leaving the column unbounded. compare_type=True did not
   catch the varchar length narrowing.

   NOTE: app/api/schemas.py caps memo input at max_length=256, one more
   than the column now holds. A 256-character memo passes Pydantic and
   fails on INSERT — a 500 where a 422 belongs. Align the two.

--------------------------------------------------------------------------
WHY THE CHECK IS A PLAIN ADD, NOT NOT VALID / VALIDATE
--------------------------------------------------------------------------
`ALTER TABLE ... ADD CONSTRAINT ... CHECK` scans every existing row while
holding ACCESS EXCLUSIVE. On a large table you want:

    ALTER TABLE accounts ADD CONSTRAINT ck_accounts_currency_format
      CHECK (currency ~ '^[A-Z]{3}$') NOT VALID;
    ALTER TABLE accounts VALIDATE CONSTRAINT ck_accounts_currency_format;

NOT VALID skips the scan; VALIDATE then performs it under a weaker lock
that does not block writes. Kept as the plain one-liner here because the
table is empty and op.create_check_constraint stays readable and trivially
reversible. Reach for the two-step form the first time this table matters.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c0e492405f67"
down_revision: str | None = "0da3c0e77b31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_check_constraint(
        op.f("ck_accounts_currency_format"), "accounts", "currency ~ '^[A-Z]{3}$'"
    )
    op.create_check_constraint(
        op.f("ck_transactions_currency_format"),
        "transactions",
        "currency ~ '^[A-Z]{3}$'",
    )
    op.create_index(
        op.f("ix_audit_events_entity_type_entity_id_created_at"),
        "audit_events",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )

    # Backfill before tightening. Autogenerate omitted this; without it the
    # ALTER fails on any pre-existing NULL memo. There is no server_default:
    # domain code always passes memo="" explicitly, so a missing memo from
    # any other path should be a loud IntegrityError, not a silent ''.
    op.execute("UPDATE transactions SET memo = '' WHERE memo IS NULL")
    op.alter_column(
        "transactions",
        "memo",
        existing_type=sa.VARCHAR(),
        type_=sa.String(255),
        nullable=False,
    )

    # Not autogenerated: Alembic does not detect primary key changes.
    # Nothing references transaction_lines, so this is a clean drop and
    # recreate with no FK dependencies to release first — unlike the
    # transactions PK swap in 0da3c0e77b31.
    op.drop_constraint(
        op.f("pk_transaction_lines"), "transaction_lines", type_="primary"
    )
    op.create_primary_key(
        op.f("pk_transaction_lines"), "transaction_lines", ["id", "created_at"]
    )

    # PRODUCTION NOTE — not needed here, needed on populated tables.
    #
    # Both the index build above and the PK recreate hold ACCESS EXCLUSIVE
    # for the duration of an index build. At scale:
    #
    #   CREATE INDEX CONCURRENTLY ix_audit_events_entity_type_entity_id_created_at
    #     ON audit_events (entity_type, entity_id, created_at);
    #
    #   CREATE UNIQUE INDEX CONCURRENTLY pk_transaction_lines_idx
    #     ON transaction_lines (id, created_at);
    #   ALTER TABLE transaction_lines ADD CONSTRAINT pk_transaction_lines
    #     PRIMARY KEY USING INDEX pk_transaction_lines_idx;
    #
    # CONCURRENTLY cannot run inside a transaction block, and
    # migrations/env.py sets transaction_per_migration=False, so this would
    # need that changed first.


def downgrade() -> None:
    # Reverses upgrade() in order. Two caveats on a populated database:
    #
    #  - PRIMARY KEY (created_at, id) is the same column set, so unlike the
    #    transactions rollback this cannot fail on duplicates.
    #  - Widening memo back to unbounded VARCHAR is lossless, but the rows
    #    backfilled from NULL to '' stay ''. The original NULLs are gone.
    #    That is accepted: '' and NULL were never meant to be distinct.
    op.drop_constraint(
        op.f("pk_transaction_lines"), "transaction_lines", type_="primary"
    )
    op.create_primary_key(
        op.f("pk_transaction_lines"), "transaction_lines", ["created_at", "id"]
    )

    op.alter_column(
        "transactions",
        "memo",
        existing_type=sa.String(255),
        type_=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_audit_events_entity_type_entity_id_created_at"),
        table_name="audit_events",
    )
    op.drop_constraint(
        op.f("ck_transactions_currency_format"), "transactions", type_="check"
    )
    op.drop_constraint(op.f("ck_accounts_currency_format"), "accounts", type_="check")
