"""add accounts table

Revision ID: 00653fcf7566
Revises:
Created: 2026-08-05 19:55:26.225288+00:00

REVIEW CHECKLIST — autogenerate is a draft, not an oracle:

  [ ] Does downgrade() actually reverse upgrade()? Test it.
  [ ] Any new index on a large table -> use postgresql_concurrently=True
      and set this migration non-transactional, or you lock writes.
  [ ] Adding a NOT NULL column to a populated table needs a server_default
      or a three-step deploy.
  [ ] Did autogenerate try to DROP something you meant to keep?
  [ ] Read the generated SQL: `alembic upgrade head --sql`
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "00653fcf7566"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normal_balance", sa.String(length=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "normal_balance IN ('debit', 'credit')",
            name=op.f("ck_accounts_normal_balance_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("name", name=op.f("uq_accounts_name")),
    )
    op.create_index(
        op.f("ix_accounts_created_at"), "accounts", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_accounts_created_at"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
