"""add transaction, transaction_line, idempotency_key, and audit_event tables

Revision ID: 7ec5c01c2ff8
Revises: 00653fcf7566
Created: 2026-08-07 00:57:38.598613+00:00

REVIEW CHECKLIST — autogenerate is a draft, not an oracle:

  [ ] Does downgrade() actually reverse upgrade()? Test it.
  [ ] Any new index on a large table -> use postgresql_concurrently=True
      and set this migration non-transactional, or you lock writes.
  [ ] Adding a NOT NULL column to a populated table needs a server_default
      or a three-step deploy.
  [ ] Did autogenerate try to DROP something you meant to keep?
  [ ] Read the generated SQL: `alembic upgrade head --sql`
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7ec5c01c2ff8"
down_revision: str | None = "00653fcf7566"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=255), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("memo", sa.String(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reverses_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reverses_id"],
            ["transactions.id"],
            name=op.f("fk_transactions_reverses_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("reverses_id", name=op.f("uq_transactions_reverses_id")),
    )
    op.create_index(
        op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_idempotency_keys_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(
        op.f("ix_idempotency_keys_created_at"),
        "idempotency_keys",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "transaction_lines",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("direction", sa.String(length=6), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=20, scale=4), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "direction IN ('debit', 'credit')",
            name=op.f("ck_transaction_lines_direction_valid"),
        ),
        sa.CheckConstraint(
            "amount > 0", name=op.f("ck_transaction_lines_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_transaction_lines_account_id_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_transaction_lines_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("created_at", "id", name=op.f("pk_transaction_lines")),
    )
    op.create_index(
        op.f("ix_transaction_lines_account_id_created_at"),
        "transaction_lines",
        ["account_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_lines_transaction_id"),
        "transaction_lines",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_transaction_lines_transaction_id"), table_name="transaction_lines"
    )
    op.drop_index(
        op.f("ix_transaction_lines_account_id_created_at"),
        table_name="transaction_lines",
    )
    op.drop_table("transaction_lines")
    op.drop_index(op.f("ix_idempotency_keys_created_at"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
